import type { Config } from "tailwindcss";
import daisyui from "daisyui";

export default {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        heading: ["Fredoka", "Comic Neue", "sans-serif"],
        sans: ["Nunito", "Comic Neue", "sans-serif"],
        sketch: ["Caveat", "cursive"],
        cinematic: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        'brutal': '4px 4px 0px 0px oklch(var(--bc) / 0.3)',
        'brutal-sm': '2px 2px 0px 0px oklch(var(--bc) / 0.3)',
        'brutal-lg': '6px 6px 0px 0px oklch(var(--bc) / 0.3)',
        'brutal-hover': '6px 6px 0px 0px oklch(var(--bc) / 0.3)',
        'cinematic': '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        'cinematic-sm': '0 10px 15px -3px rgba(0, 0, 0, 0.3)',
        'cinematic-lg': '0 35px 60px -15px rgba(0, 0, 0, 0.6)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.5)',
      },
      borderWidth: {
        '3': '3px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        doodle: {
          "primary": "#FFDE59",
          "primary-content": "#1a1a1a",
          "secondary": "#FF71CE",
          "secondary-content": "#1a1a1a",
          "accent": "#00D9FF",
          "accent-content": "#1a1a1a",
          "neutral": "#1a1a1a",
          "neutral-content": "#ffffff",
          "base-100": "#FFFEF0",
          "base-200": "#FFF9E0",
          "base-300": "#FFF3C4",
          "base-content": "#1a1a1a",
          "info": "#00D9FF",
          "info-content": "#1a1a1a",
          "success": "#7CFC00",
          "success-content": "#1a1a1a",
          "warning": "#FF9F1C",
          "warning-content": "#1a1a1a",
          "error": "#FF5757",
          "error-content": "#ffffff",
        },
      },
      {
        "doodle-dark": {
          "primary": "#FFDE59",
          "primary-content": "#1a1a1a",
          "secondary": "#FF71CE",
          "secondary-content": "#1a1a1a",
          "accent": "#00D9FF",
          "accent-content": "#1a1a1a",
          "neutral": "#2a2a2a",
          "neutral-content": "#ffffff",
          "base-100": "#1a1a1a",
          "base-200": "#2a2a2a",
          "base-300": "#3a3a3a",
          "base-content": "#ffffff",
          "info": "#00D9FF",
          "info-content": "#1a1a1a",
          "success": "#7CFC00",
          "success-content": "#1a1a1a",
          "warning": "#FF9F1C",
          "warning-content": "#1a1a1a",
          "error": "#FF5757",
          "error-content": "#ffffff",
        },
      },
      {
        "cinematic": {
          "primary": "#3B82F6",
          "primary-content": "#ffffff",
          "secondary": "#8B5CF6",
          "secondary-content": "#ffffff",
          "accent": "#EC4899",
          "accent-content": "#ffffff",
          "neutral": "#0F172A",
          "neutral-content": "#F1F5F9",
          "base-100": "#0B0F19",
          "base-200": "#111827",
          "base-300": "#1F2937",
          "base-content": "#E2E8F0",
          "info": "#0EA5E9",
          "info-content": "#ffffff",
          "success": "#10B981",
          "success-content": "#ffffff",
          "warning": "#F59E0B",
          "warning-content": "#ffffff",
          "error": "#EF4444",
          "error-content": "#ffffff",
        },
      },
      {
        "cinematic-light": {
          "primary": "#2563EB",
          "primary-content": "#ffffff",
          "secondary": "#7C3AED",
          "secondary-content": "#ffffff",
          "accent": "#DB2777",
          "accent-content": "#ffffff",
          "neutral": "#1E293B",
          "neutral-content": "#F8FAFC",
          "base-100": "#F8FAFC",
          "base-200": "#F1F5F9",
          "base-300": "#E2E8F0",
          "base-content": "#1E293B",
          "info": "#0284C7",
          "info-content": "#ffffff",
          "success": "#059669",
          "success-content": "#ffffff",
          "warning": "#D97706",
          "warning-content": "#ffffff",
          "error": "#DC2626",
          "error-content": "#ffffff",
        },
      },
    ],
    darkTheme: "doodle-dark",
  },
} satisfies Config;
