from __future__ import annotations

from .character import SYSTEM_PROMPT as CHARACTER_SYSTEM_PROMPT
from .director import SYSTEM_PROMPT as DIRECTOR_SYSTEM_PROMPT
from .onboarding import SYSTEM_PROMPT as ONBOARDING_SYSTEM_PROMPT
from .scriptwriter import SYSTEM_PROMPT as SCRIPTWRITER_SYSTEM_PROMPT
from .storyboard import SYSTEM_PROMPT as STORYBOARD_SYSTEM_PROMPT

__all__ = [
    "CHARACTER_SYSTEM_PROMPT",
    "DIRECTOR_SYSTEM_PROMPT",
    "ONBOARDING_SYSTEM_PROMPT",
    "SCRIPTWRITER_SYSTEM_PROMPT",
    "STORYBOARD_SYSTEM_PROMPT",
]

